ecommerce/cart/urls.py
from django.urls import path
from . import views
app_name='cart'

urlpatterns = [
    path('addtocart/<int:id>', views.add_to_cart, name='addtocart'),
    path('viewcart', views.viewcart, name='viewcart'),
    path('removecart/<int:id>', views.remove_from_cart, name='removecart'),
    path('deletecart/<int:id>', views.delet_from_cart, name='deletcart'),
    path('placeorder', views.place_order, name='placeorder'),
    path('success/<u>', views.payment_status, name='success'),
    path('yourorders',views.your_orders,name='yourorders')

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='search'
urlpatterns = [

    path('search',views.search,name='search')
    ]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='shop'


urlpatterns = [
    path('',views.home,name='home'),
    path('catagory',views.catagory,name='catagory'),
    path('product/<int:id>',views.product,name='product'),
    path('productdetails/<int:id>',views.productdetails,name='productdetails'),
    path('user_login', views.user_login, name='user_login'),
    path('registration', views.registration, name='registration'),
    path('user_logout', views.user_logout, name='user_logout'),

]

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product

# Create your views here.
def search(request):
    p=None
    s=''
    if (request.method=='POST'):
        s=request.POST['search']
        if s:
            p=Product.objects.filter(p_name__icontains=s)
    return render(request,'search.html',{'p':p})

ecommerce/templates/base.html
<!--header starts-->
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Eflyer</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- fonts -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
      <!-- font awesome -->
      <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <!--  -->
      <!-- owl stylesheets -->
      <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
   </head>
   <body>
      <!-- banner bg main start -->
      <div class="banner_bg_main">
         <!-- header top section start -->
         <div class="container">
            <div class="header_section_top">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="custom_menu">
                        <ul>
                           <li><a href="{% url 'shop:home' %}">Home</a></li>
                           <li><a href="{% url 'shop:catagory' %}">Category</a></li>
                           <li><a href="{% url 'shop:user_login' %}">Login</a></li>
                           <li><a href="{% url 'cart:yourorders' %}">Yours Orders</a></li>
                           <li><a href="{% url 'shop:registration' %}">Registration</a></li>
                           <li><a href="{% url 'shop:user_login' %}">Logout</a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- header top section start -->
         <!-- logo section start -->
         <div class="logo_section">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="logo"><a href="index.html"><img src="{% static 'images/logo.png' %}"></a></div>
                  </div>
               </div>
            </div>
         </div>
         <!-- logo section end -->
         <!-- header section start -->
         <div class="header_section">
            <div class="container">
               <div class="containt_main pb-4">
                  <div id="mySidenav" class="sidenav">
                     <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                     <a href="index.html">Home</a>
                     <a href="fashion.html">Fashion</a>
                     <a href="electronic.html">Electronic</a>
                     <a href="jewellery.html">Jewellery</a>
                  </div>
                  <span class="toggle_icon" onclick="openNav()"><img src="{% static 'images/toggle-icon.png' %}"></span>
                  <div class="dropdown">
                     <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category
                     </button>
                     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        {% for i in links %}
                        <a class="dropdown-item" href="{% url 'shop:product' i.id %}">{{i.name}}</a>
<!--                        <a class="dropdown-item" href="#">Another action</a>-->
<!--                        <a class="dropdown-item" href="#">Something else here</a>-->
                        {% endfor %}
                     </div>
                  </div>
                  <div class="main">
                     <form method="post" action="{% url 'search:search' %}">
                           {% csrf_token %}
                     <!-- Another variation with a button -->
                     <div class="input-group">

                        <input type="text" class="form-control" placeholder="Search this blog" name="search">
                        <div class="input-group-append">
                           <button class="btn btn-secondary" type="submit" style="background-color: #f26522; border-color:#f26522 ">
                           <i class="fa fa-search"></i>
                           </button>
                        </div>
                     </div>
                     </form>

                  </div>
                  <div class="header_box">
                     <div class="lang_box ">
                        <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                        <img src="{% static 'images/flag-uk.png' %}" alt="flag" class="mr-2 " title="United Kingdom"> English <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu ">
                           <a href="#" class="dropdown-item">
                           <img src="{% static 'images/flag-france.png' %}" class="mr-2" alt="flag">
                           French
                           </a>
                        </div>
                     </div>
                     <div class="login_menu">
                        <ul>
                           <li><a href="{% url 'cart:viewcart' %}">
                              <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                              <span><sup style="color:black">{{count}}</sup></span></a>
                           </li>

                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>


<!-- header ends-->
          {% block content %}

          {% endblock %}

<!-- footer section starts-->
                <div class="footer_section layout_padding">
         <div class="container">
            <div class="footer_logo"><a href="index.html"><img src="{% static 'images/footer-logo.png' %}"></a></div>
            <div class="input_bt">
               <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
               <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
            </div>
            <div class="footer_menu">
               <ul>
                  <li><a href="#">Best Sellers</a></li>
                  <li><a href="#">Category</a></li>
                  <li><a href="#">New Releases</a></li>
                  <li><a href="#">Today's Deals</a></li>
                  <li><a href="#">Customer Service</a></li>
               </ul>
            </div>
            <div class="location_main">Help Line  Number : <a href="#">+1 1800 1200 1200</a></div>
         </div>
      </div>
      <!-- footer section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html  Templates</a></p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <script>
         function openNav() {
           document.getElementById("mySidenav").style.width = "250px";
         }

         function closeNav() {
           document.getElementById("mySidenav").style.width = "0";
         }
      </script>
   </body>
</html>
<!--footer section ends-->

ecommerce/templates/catagory.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
         <div class="banner_section layout_padding">
            <div class="container">
               <div id="my_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                  <i class="fa fa-angle-left"></i>
                  </a>
                  <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                  <i class="fa fa-angle-right"></i>
                  </a>
               </div>
            </div>
         </div>
         <!-- banner section end -->
<div class="row">
   {% for i in cat %}
   <div class="col-lg-4 col-sm-4">
      <div class="box_main">
         <h4 class="shirt_text">{{i.name}}</h4>
         <p class="price_text">{{i.desc}} </p>
         <div style="height:300px" class="tshirt_img border border-2" >
            <img src="{{i.image.url}}" style="height:100%;width:100%">
         </div>
         <div class="btn_main">
            <div class="buy_bt"><a href="{% url 'shop:product' i.id %}">Buy Now</a></div>

         </div>
      </div>
   </div>
{% endfor %}
</div>


{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
      <div class="row">
          <div class="col">
              <form method="post" class="container">
                  {% csrf_token %}
                  <div class=" mb-3">
                      <label for="exampleInputEmail1" class="form-label">User Name</label>
                      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="u">
                  </div>
                  <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword1" name="p">
                  </div>
                  <input type="submit" class="btn btn-secondary">
              </form>
          </div>
          <div class="col">
              <img src="{% static 'images/wallet.jpg' %}" style="height:100%;width:100%">
          </div>
      </div>
</div>

{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="bg-primary " style="padding-left:500px" >
<form action="http://127.0.0.1:8000/cart/success/{{payment.name}}" method="POST">
    {% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_7kdmsrPGYoAenp"
    data-amount="{{payment.amount}}"
    data-currency="{{payment.currency}}"
    data-order_id="{{payment.id}}"

    data-buttontext="Pay Now"
    data-name="Eflyer"
    data-description="Dressing is an art"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>
{% endblock %}

ecommerce/templates/placeorder.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<div class="container " style="h">
      <div class="row">
          <div class="col">
              <form method="post" class="container" style="width:100px height:100px">
                  {% csrf_token %}
                  <div class=" mb-3">
                      <label for="exampleInputEmail1" class="form-label">Phone No</label>
                      <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="p">
                  </div>
                  <div class="mb-3">
                      <label for="exampleInputPassword2" class="form-label">Delivery Address</label>
                      <input type="text" class="form-control" id="exampleInputPassword2" name="a">
                  </div>
                   <div class="mb-3">
                      <label for="exampleInputPassword3" class="form-label">Pincode</label>
                      <input type="number" class="form-control" id="exampleInputPassword3" name="pin">
                  </div>
                  <input type="submit" class="btn btn-secondary">
              </form>
          </div>
      </div>
    </div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
               <div class="banner_section layout_padding">
            <div class="container">
               <div id="my_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                              <div class="buynow_bt"><a href="#">Buy Now</a></div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                  <i class="fa fa-angle-left"></i>
                  </a>
                  <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                  <i class="fa fa-angle-right"></i>
                  </a>
               </div>
            </div>
         </div>
         <!-- banner section end -->

     <div class="container-fluid" >
         <img src="{{cat.image.url}}" style="height:600px;width:100%">
     </div>
<div class="row ">
   {% for i in pro %}
   <div class="col-lg-4 col-sm-4 ">
      <div class="box_main">
         <h4 class="shirt_text">{{i.p_name}}</h4>
         <p class="price_text">DESCRIPTION:{{i.p_desc}} </p>
         <p class="price_text">PRICE:{{i.p_price}} </p>
          <div style="height:300px" class="tshirt_img border border-2" >
            <img src="{{i.p_image.url}}" style="height:100%;width:100%">
         </div>
         <p class="price_text">AVAILABILITY:{{i.p_stock}} </p>

         <div class="btn_main">
            <div class="buy_bt"><a href="{% url 'shop:productdetails' i.id %}">View Details</a></div>

         </div>
      </div>
   </div>
{% endfor %}
</div>

{% endblock %}

ecommerce/templates/productdetails.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
      <div class="row">
          <div class="col">
      <img src="{{pro1.p_image.url}}" style="height:100%;width:100%">
          </div>
      <div class="col">
         <h1>{{pro1.p_name}}</h1>
         <p>{{pro1.p_desc}}</p>
          <p>{{pro1.p_price}}</p>
          <h2>Available Stock:{{pro1.p_stock}}</h2>
          {% if pro1.p_stock > 0 %}
                <p>AVAILABLE</p>
          {% else %}
                <p>UNAVAILABLE</p>
          {% endif %}
          <a href="{% url 'cart:addtocart' pro1.id %}"><button class="btn bg-primary">Add To Cart</button></a>
      </div>

      </div>
</div>
{% endblock %}

ecommerce/templates/registration.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">

      <div class="row">
          <div class="col">
      <img src="{% static 'images/reg.jpg' %}" style="height:100%;width:100%">
          </div>
      <div class="col">
         <form method="post" class="container ">
  {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label" style="color:white">User Name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="u">

  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label" style="color:white">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="p">
  </div>
    <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label" style="color:black">Confirm Password</label>
    <input type="password" class="form-control" id="exampleInputPassword2" name="cp">
  </div>
    <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label" style="color:black">First Name</label>
    <input type="text" class="form-control" id="exampleInputPassword3" name="fname">
  </div>
    <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label" style="color:black">Last Name</label>
    <input type="text" class="form-control" id="exampleInputPassword4" name="lname">
  </div>
    <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label" style="color:black">E-Mail</label>
    <input type="email" class="form-control" id="exampleInputPassword5" name="email">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

      </div>

      </div>
</div>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="row">
   {% for i in p %}
   <div class="col-lg-4 col-sm-4">
      <div class="box_main">
         <h4 class="shirt_text">{{i.p_name}}</h4>
         <p class="price_text">{{i.p_desc}} </p>
          <div style="height:300px" class="tshirt_img border border-2" >
            <img src="{{i.p_image.url}}" style="height:100%;width:100%">
         </div>
         <p class="price_text">{{i.p_stock}} </p>

         <div class="btn_main">
            <div class="buy_bt"><a href="{% url 'shop:productdetails' i.id %}">View Details</a></div>

         </div>
      </div>
   </div>
{% endfor %}
</div>

{% endblock %}

ecommerce/templates/success.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


{% if status == True %}
<h1> PAYMENT SUCCESS</h1>
{% else %}
<h1>PAYMENT FAILED</h1>
{% endif %}

{% endblock %}

ecommerce/templates/viewcart.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

	<div class="row  ">
		<div class="col-7 " >
			<div class="container mt-5 pt-5 " >
				<table class="table table-bordered border-dark">
					<tr>
						<th style="color:black;">Cart Items</th>
					</tr>
					{% for i in cart %}
					<tr style="color:black;">
						<td style="color:black;"><a href="{% url 'shop:productdetails' i.product.id %}" ><img src="{{i.product.p_image.url}}" height="50px" width="100px" ></a> </td>
						<td style="color:black;">Product Name:{{i.product.p_name}}</td>
						<td style="color:black;">Product Id:{{i.product.id}}</td>
						<td style="color:black;">Quantity:{{i.quantity}} <br> Unit Price:{{i.product.p_price}}</td>
						<td style="color:black;">Subtotal:{{i.subtotal}}</td>

						<td style="color:black;">
							{% if i.product.p_stock > 0 %}
							<a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus"> </i></a> <br>
							<a href="{% url 'cart:removecart' i.product.id %}"><i class="fa-solid fa-circle-minus"></i></a> <br>
							<a href="{% url 'cart:deletcart' i.product.id  %}"><i class="fa-solid fa-trash-can"></i></a>
							{% else %}
							    	<a href="{% url 'cart:removecart' i.product.id %}"><i class="fa-solid fa-circle-minus"></i></a> <br>
							      <a href="#"><i class="fa-solid fa-trash-can"></i></a>
							{% endif %}

						</td>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
		<div class="col-5">
			<div class="container mt-5 pt-5">
				<table class="table table-bordered" style="width:50%;">
					<tr>
						<th style="color:black;">CheckOut</th>
					</tr>
					<tr>
						<th style="color:black;">Total Amount :{{total}} </th>
					</tr>
				</table>
				<a href="{% url 'cart:placeorder' %}" class="btn  bg-dark " style="color:white">Place Order</a>
				<a href="{% url 'shop:home' %}" class="btn bg-dark " style="color:white">Continue Shopping</a>
			</div>
		</div>
	</div>
</section>

{% endblock %}

ecommerce/templates/yourorders.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container mt-5 mb-5">
{% for i in orders %}
	<div class="row border">

    	<div class="col-5">
      		<img class="img-fluid" src="{{i.product.p_image.url}}" style="height:200px" alt="">
		</div>
    	<div class="col-6">
			<p class="fw-bold">Product Name : {{i.product.p_name}}</p>
			<p class="fw-bold">Price : {{i.product.p_price}}</p>
			<p class="fw-bold">Ordered On : {{i.ordered_date}}</p>
			<p class="fw-bold">Delivery Status : {{i.delivery_status}}</p>
		</div>

	</div>
	{% endfor %}

</div>

{% endblock %}